### ISSUE TITLE
速度有点慢，可以进行并发破解吗?

### ISSUE THREAD

**Issue by zerostwo** [General-Lai/SicauPasswordAttack#1]

**Comment by General-Lai** [comment]
你欺负我不会php多线程哦：)

**Comment by zerostwo** [comment]
> 你欺负我不会php多线程哦：)



> 你欺负我不会php多线程哦：)

hahah，我不懂php，之前我用python写了个和你思路差不多的但我的是多线程并发的，准备把全校的默认密码都做出来，但是多线程并发导致timeout的几率增加，也不高效，所以我就随便跑到了1000多个就停止了。
ps：为什么你成都理工的会来写个爆破川农教务处的密码呢😂

**Comment by General-Lai** [comment]
我朋友也是川农的，他硬要让我找你们学校的漏洞，我找了半天也没发现啥漏洞。
最后写了个暴力破解玩，嘿嘿嘿嘿....
